name = "Ducc0"
uuid = "47ec601d-2729-4ac9-bed9-2b3ab5fca9ff"
authors = ["Martin Reinecke <martin@MPA-Garching.MPG.DE>", "Maurizio Tomasi <ziotom78@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ducc0_jll = "744a402c-e62c-509f-85e0-10e6c18f2016"

[compat]
julia = "1.6"
ducc0_jll = "0.29.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Healpix", "LinearAlgebra", "Random"]
