name = "Ducc0"
uuid = "47ec601d-2729-4ac9-bed9-2b3ab5fca9ff"
authors = ["Martin Reinecke <martin@MPA-Garching.MPG.DE>", "Maurizio Tomasi <ziotom78@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ducc0_jll = "0.27.9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
